default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgres") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: 5432

development:
  primary:
    <<: *default
    database: oh_my_jetlag_development
  queue:
    <<: *default
    database: oh_my_jetlag_development

test:
  <<: *default
  database: oh_my_jetlag_test

production:
  <<: *default
  database: app_production
  url: <%= ENV["DATABASE_URL"] %>
